# Generated by Django 3.2 on 2021-04-19 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nessues_app', '0003_task_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='table',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
